### ISSUE TITLE
Add app to GPlay and F-Droid

### ISSUE THREAD

**Issue by pacien** [pacien/tincapp#1]
- [x] Google Play (https://play.google.com/store/apps/details?id=org.pacien.tincapp)
- [x] F-Droid (https://gitlab.com/fdroid/rfp/issues/133)

**Comment by relan** [comment]
F-Droid cannot build [0.1-preview](https://f-droid.org/wiki/page/org.pacien.tincapp/lastbuild_1) becase it does not have `constraint-layout:1.0.0-alpha4` installed. Please update `constraint-layout` dependency to 1.0.2. To make F-Droid pick a new release, bump versionCode, versionName and tag a new release.

**Comment by Daniel-at-github** [comment]
Seen on F-Droid in https://f-droid.org/repository/browse/?fdid=org.pacien.tincapp

**Comment by pacien** [comment]
Old version of `constraint-layout` seems to have been added to F-Droid's build servers before I could update it here. I will still update to the latest stable release soon.

Thanks for letting me know!

**Comment by relan** [comment]
0.2 and 0.3 are already on F-Droid without this hack. Thanks!

**Comment by KOLANICH** [comment]
the app is not updated in f-droid

**Comment by relan** [comment]
> the app is not updated in f-droid

The latest version is 0.7 and it's available on F-Droid: https://f-droid.org/packages/org.pacien.tincapp/

**Comment by KOLANICH** [comment]
the latest **release** version.
