### ISSUE TITLE
Battery Optimization causes unstable connection

### ISSUE THREAD

**Issue by jalius** [pacien/tincapp#101]
Battery Optimization on my Android 9 device was breaking the tinc connection whenever the Tinc App was minimized for a period of time. This created a confusing and unstable connection during the setup process. I would go to load a web service and it would load halfway and then break connection. I had to disable Battery Optimization in Android settings for Tinc App and now everything is fine. 

I have no idea how to address this, as I'm not familiar with the Android api and what is possible from an app. Can there be a setup step to disable battery optimization or at least prompt the user to disable it to improve the user experience?

**Comment by jalius** [comment]
https://developer.android.com/reference/android/provider/Settings#ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS

**Comment by jalius** [comment]
I suppose this could also be noted in the [Troubleshooting Guide](https://tincapp.pacien.org/troubleshooting.html)

**Comment by pacien** [comment]
Hello and thank you for the suggestions;
I've added an entry in the FAQ section of the website.

Adapting the underlying tinc daemon for Android's specific battery-optimised
network scheduling might be quite complicated.

It would indeed be sufficient to display a prompt within the application
if the "battery optimisation" feature is enabled for the app.

**Comment by pacien** [comment]
Note: Google Play seems to be kicking applications which make use of the `ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` intent.

---

I couldn't replicate the problematic behaviour with both the "App Standby" and "Doze" mode on AOSP from version 6 to 11.
@jalius On which device (manufacturer and model) are you experiencing the described issue?

**Comment by pacien** [comment]
The problem only seems to affect some device manufacturers who ship customised Android ROMs with more aggressive power management rules than the ones in AOSP.

Detecting which particular devices are affected doesn't seem straightforward, making it hard to display a warning only when needed.

I added some extra details and remediation procedures to the documentation which should be enough to guide the users who are experiencing this issue.

**Comment by jalius-alt** [comment]
Just for reference I'm on OnePlus 6t with stock firmware. I checked and this phone does ship with the custom Android 9 ROM called OxygenOS 9.0.17.

**Comment by jalius** [comment]
Ok, thanks pacien. Just for reference I'm on OnePlus 6t with stock manufacturer firmware. This phone does ship with a custom Android 9 ROM called OxygenOS 9.0.17.
