### ISSUE TITLE
Select default trafic route. (feature request)

### ISSUE THREAD

**Issue by link0ln** [pacien/tincapp#104]
Is it good idea to make option to select default route, if found more than 1 node with 0.0.0.0/0 route?
For example I have multiple nodes with same routes (0.0.0.0/0), but trafic is going through first node of list sorted by name. I think it can be manually managed by set priority of same routes.

**Comment by pacien** [comment]
tinc already allows different priorities to be assigned to subnets on different nodes:

> ```
> Subnet = <address[/prefixlength[#weight]]>
> ```
>
> […]
>
> A Subnet can be given a weight to indicate its priority over identical Subnets owned by different nodes.
> The default weight is 10.
> Lower values indicate higher priority.
> Packets will be sent to the node with the highest priority, unless that node is not reachable,
> in which case the node with the next highest priority will be tried, and so on.
>
> – https://tinc-vpn.org/documentation-1.1/Host-configuration-variables.html#Host-configuration-variables

**Comment by link0ln** [comment]
Yes, this solution is working well, but cant be managed dynamically. Maybe it can be managed by for example clicking on routes inside app?

**Comment by pacien** [comment]
This doesn't seem to be supported by the underlying tinc daemon.
Alternatively, you can make a copy of a tinc network with a different name and different routes and switch between those networks.

**Comment by link0ln** [comment]
hmm, ok, thank you for quick answers !!
