### ISSUE TITLE
Not specifying any IPv4 address breaks IPv4 connectivity

### ISSUE THREAD

**Issue by twisteroidambassador** [pacien/tincapp#105]
I have a tinc network that only uses IPv6 internal addresses. `network.conf` only contains one Address line specifying the IPv6 address (/128) and one Network line specifying the /64 subnet.

As soon as I connect to the network, all IPv4 connectivity fails. Trying to ping IPv4 addresses or hostnames result in "no route to host".

When another Address line specifying an IPv4 address is added to `network.conf`, IPv4 works again when connected.

**Comment by pacien** [comment]
You can enable an address family without specifying an address with `AllowFamily`.

I assume that you want to keep some IPv4 connectivity outside of the VPN while using IPv6 inside the VPN (otherwise you'd need to give an IPv4 address to the device anyway). For this, you'd probably also need to enable `AllowBypass`.

Your `network.conf` file would have:

```ini
Address = some:ipv6:address/128
AllowFamily = 2
AllowBypass = true
```

Relevant documantion from https://tincapp.pacien.org/doc.html#network-interface:
> `AllowFamily = [2|10]`
> Allows traffic from the specified address family. By default, if no address, route or DNS server of a specific family (IPv4 or IPv6) is added to this VPN, then all outgoing traffic of that family is blocked. If any address, route or DNS server is added, that family is allowed. This method allows an address family to be unblocked even without adding an address, route or DNS server of that family. Traffic of that family will then typically fall-through to the underlying network if it’s supported. Family must be either AF_INET (for IPv4) or AF_INET6 (for IPv6), for which integer values are respectively 2 and 10.
>
> `AllowBypass = [true|false]`
> Allows all apps to bypass this VPN connection. By default, all traffic from apps is forwarded through the VPN interface and it is not possible for apps to side-step the VPN. If this parameter is set to true, apps may send/receive directly over the underlying network or any other network they have permissions for.

**Comment by twisteroidambassador** [comment]
Thanks for the information.
One more question though: right now, I have added one IPv4 Address, and have not specified AllowBypass (so it should be defaulted to false). I do have IPv4 connectivity to the internet this way. From the wording of AllowBypass, it seems like connectivity to IPv4 internet should be blocked in this case?

**Comment by pacien** [comment]
`AllowFamily` indeed has precedence over `AllowBypass` in allowing traffic of a specific family to go aside of the VPN; my bad!
I've updated the documentation to clarify this.

**Comment by twisteroidambassador** [comment]
To be precise, I had this `network.conf` for a while:
```
Address = some:ipv6:address::1/128
Address = some.ipv4.address/32
Route = some:ipv6:address::/64
```

I did not specify AllowBypass or AllowFamily in the file, yet I still have IPv4 Internet connectivity. Is this to be expected?

**Comment by pacien** [comment]
In this case, connectivity to the VPN is expected, but not to the Internet directly.

**Comment by twisteroidambassador** [comment]
I just tested this config again. Running traceroute to 8.8.8.8, I can see the first hop is my router's local address, so internet traffic is not traveling through the VPN. Is this a bug then?

This is with Tinc App version 0.31 on Android 10, on a Redmi Note 7 device flashed with Pixel Experience ROM.

**Comment by pacien** [comment]
It might be a bug in the particular ROM that you're using, or even Android itself, which defines and controls this behaviour.
All that Tinc App does is expose and forward the configuration to the [underlying system VPN service API][1].

[1]: http://developer.android.com/reference/android/net/VpnService.Builder.html

We don't have much/any control over this at the application level.
If the ROM that you're using is close to AOSP, you can report the issue to the Android project.

**Comment by twisteroidambassador** [comment]
Well if that's not the app's problem, I'll close this issue. Thanks!
