### ISSUE TITLE
tincd.exe crash on Windows related to bcryptPrimitives.dll

### ISSUE THREAD

**Issue by twisteroidambassador** [pacien/tincapp#109]
`tincd.exe` would simply exit randomly on Windows 10. I got these from Event Viewer:

    Faulting application name: tincd.exe, version: 0.0.0.0, time stamp: 0x61eeb032
    Faulting module name: bcryptPrimitives.dll, version: 10.0.19041.1415, time stamp: 0xe9d3d417
    Exception code: 0xc0000005
    Fault offset: 0x0000000000025a63
    Faulting process id: 0x3280
    Faulting application start time: 0x01d82ca88e24270f
    Faulting application path: C:\Program Files\tinc\tincd.exe
    Faulting module path: C:\Windows\System32\bcryptPrimitives.dll
    Report Id: [removed]
    Faulting package full name: 
    Faulting package-relative application ID: 

Event viewer mentions a memory dump file, but I was not able to retrieve it.

This is on Windows 10 21H2 19044.1526 and `tinc version 1.1pre18-116-ge856b04f (built Jan 24 2022 13:57:06, protocol 17.7)`.

**Comment by olifre** [comment]
Hi,
this repository is about the `tincapp` for Android, i.e. not about `tincd` itself. Your issue will be seen by the Tinc developers via the official Tinc mailing list, please see the "Report bugs" bullet point at:
https://www.tinc-vpn.org/contribute/

That said, you'll probably want to run `tincd` with a high debug level to check whether the crash can be correlated to some debug output, Concerning application crashdumps on Windows, the following article may be helpful:
https://helgeklein.com/blog/creating-an-application-crash-dump/
