### ISSUE TITLE
Configuration problems on Android 14

### ISSUE THREAD

**Issue by Ratio2** [pacien/tincapp#122]
Pixel 8
v0.38

1. When creating a new configuration, the private keys and host file are not readable, conf files ok (USB cable on PC, Ghost Commander via SAF).
2. Files can only be accessed via Ghost Commander/SAF if you restore the Files application to factory version.

It looks like deleting the FTP server was premature.

**Comment by pacien** [comment]
Hi,
that should be resolved by commit 94f3a07b20019a7d412bb1b5caa4f5ce153732a9.
Please try release v0.39.
