### ISSUE TITLE
Add Intents for integration with automation Android apps

### ISSUE THREAD

**Issue by rvaidya** [pacien/tincapp#17]
Apps like Tasker, Automate, and Llama can call Intents on other applications - having intents for starting a tinc net and stopping tinc would be awesome, as then we can use these powerful apps to start/stop tinc on whatever conditions we want.

**Comment by rvaidya** [comment]
My knowledge of Android dev is pretty limited but to do this it sounds like you'd have to refactor starting service / stopping service into separate activities that have no UI and can filter on some intent name.

**Comment by rvaidya** [comment]
Nevermind, I've looked into this a bit more, this may not be possible due to Android permissions

**Comment by pacien** [comment]
Interesting, this could replace the feature described in issue #3 (Automatic tinc network selection).

A blank activity could act as a proxy and receive such external intent, show a permission request dialog and/or ask for a passphrase to unlock private keys (issue 19) if needed, then start/stop the service.

---

Do you know any open-source application similar to those that you mentionned?

**Comment by rvaidya** [comment]
This one might work https://github.com/biotinker/LibreTasks

**Comment by rvaidya** [comment]
The free but not open source ones like automate will probably have more
functionality

**Comment by pacien** [comment]
Added (commit ac289a9, release v0.4).

**Comment by rvaidya** [comment]
Thanks, it works!

Attached are my Tasker profiles for connect/disconnect.
[Tinc.zip](https://github.com/pacien/tincapp/files/1235533/Tinc.zip)
