### ISSUE TITLE
[Feature Request] Show Log by click on button

### ISSUE THREAD

**Issue by Mannshoch** [pacien/tincapp#26]
With a kill command and INT as signal you could set tinc instant to loglevel 5 a second INT move it back.

Would be nice if you could combinate it with a log window that show the log "tinc.NETNAME.log" and present an _Increase log_ and _export_ button.

http://tinc-vpn.org/documentation/Signals.html#Signals

**Comment by pacien** [comment]
Simple log viewer added with commit c6de35b, release v0.11.
