### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by yangfl** [pacien/tincapp#28]
When I mistyped `Route = 10.0.0.1/24`, it just complains `Bad address` and nothing else. I have to check every CIDR until I realised what was wrong.

It would better if the parser could give more information, like line no.

**Comment by pacien** [comment]
Indeed, I will print the faulty line or its line number along the error message.

**Comment by pacien** [comment]
Erroneous address/route configuration entries are now displayed in error messages.
Commit ref 70ee334, part of tincapp release v0.10.
