### ISSUE TITLE
Gateway/Routing support

### ISSUE THREAD

**Issue by yangfl** [pacien/tincapp#31]
Is there any support for changing default gateway? I can't find it in the manual.

It's extremely disappointing for an VPN software to have no support for default gateway.

I would like to suggest something like

`ip route add 10.0.0.0/24 via 10.0.0.1 dev $INTERFACE     ->  Route = 10.0.0.0/24 10.0.0.1`

**Comment by pacien** [comment]
`Route 0.0.0.0/0` in `network.conf` and in your gateway's tinc host file.
Please use the IRC channel for further assistance if required.
