### ISSUE TITLE
Hope the app itself can generate invitation

### ISSUE THREAD

**Issue by Sak94664** [pacien/tincapp#34]
If the app can generate invitation itself in the Graphical interface ,it would be great!

PS.
Forgot to add [feature request] tag,sorry!

**Comment by pacien** [comment]
The generated invitation URL would be dependent on the node's IP address stability and reachability. This makes the use of this feature practically impossible on mobile devices.

**Comment by Sak94664** [comment]
Sounds reasonable. :)
But I don't know how to combine two android device.Could you please tell me how to do it?(Want to have a detailed example),thanks!
(sorry for my poor English)

**Comment by pacien** [comment]
You'd need to generate configurations on both devices, then exchange the host files.
They'd be able to discover each other only when on the same network. To enable communication through an external one, a third fixed host (with an external reachable and stable address) is recommended.
Procedures are described in tinc's documentation and website.
If you need further assistance, please use the mailing lists or the IRC channels.
