### ISSUE TITLE
Missing network config

### ISSUE THREAD

**Issue by gerroon** [pacien/tincapp#36]
HI

I am trying to use this app, so I click to generate the configs. It creates the configs then complaints about missing network.conf.

I use it on Android 5.1

thanks

**Comment by pacien** [comment]
Hello,
You need to create and edit this file manually to configure your network interface.

---

To avoid further confusion, a template file will be generated as well in a future version of this app.

**Comment by gerroon** [comment]
Thanks, that would be great. As a basic user I would really prefer if the app considers that people who are using this app are just stupid and creates the necessary stuff to go forward.

**Comment by pacien** [comment]
Template generation added with commit eb31e37, for release v0.11.
