### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by CoterJiesen** [pacien/tincapp#37]
:app:externalNativeBuildDebug
Build exec arm64-v8a
[
1
/
2
0
]
 
P
e
r
f
o
r
m
ing configure step for 'lzo'
[2/20] No update step for 'libressl'
[3/20] No patch step for 'libressl'
FAILED: cmd.exe /C "cd /D D:\tincapp-master\app\.externalNativeBuild\cmake\debug\arm64-v8a\lzo-prefix\src\lzo-build && D:\tincapp-master\app\.externalNativeBuild\cmake\debug\arm64-v8a\lzo-prefix\src\lzo\configure "CC=E:/work/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe 		--gcc-toolchain=E:/work/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 		--target=aarch64-none-linux-android 		--sysroot=E:/work/Android/sdk/ndk-bundle/sysroot" LD=E:/work/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/aarch64-linux-android-ld.exe AR=E:/work/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/aarch64-linux-android-ar.exe RANLIB=E:/work/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/aarch64-linux-android-ranlib.exe "CFLAGS=-isystem E:/work/Android/sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security " "LDFLAGS=-Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot E:/work/Android/sdk/ndk-bundle/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now " --host=aarch64-none-linux-android --disable-shared && E:\work\Android\sdk\cmake\3.6.4111459\bin\cmake.exe -E touch D:/tincapp-master/app/.externalNativeBuild/cmake/debug/arm64-v8a/lzo-prefix/src/lzo-stamp/lzo-configure"
'D:\tincapp-master\app\.externalNativeBuild\cmake\debug\arm64-v8a\lzo-prefix\src\lzo\configure' ????????????????????????е????
?????????????
ninja: build stopped: subcommand failed.
:app:externalNativeBuildDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process E:\work\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\tincapp-master\app\.externalNativeBuild\cmake\debug\arm64-v8a --target exec}
  [1/20] Performing configure step for 'lzo'
  [2/20] No update step for 'libressl'
  [3/20] No patch step for 'libressl'
  FAILED: cmd.exe /C "cd /D D:\tincapp-master\app\.externalNativeBuild\cmake\debug\arm64-v8a\lzo-prefix\src\lzo-build && D:\tincapp-master\app\.externalNativeBuild\cmake\debug\arm64-v8a\lzo-prefix\src\lzo\configure "CC=E:/work/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe 		--gcc-toolchain=E:/work/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 		--target=aarch64-none-linux-android 		--sysroot=E:/work/Android/sdk/ndk-bundle/sysroot" LD=E:/work/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/aarch64-linux-android-ld.exe AR=E:/work/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/aarch64-linux-android-ar.exe RANLIB=E:/work/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/aarch64-linux-android-ranlib.exe "CFLAGS=-isystem E:/work/Android/sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security " "LDFLAGS=-Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot E:/work/Android/sdk/ndk-bundle/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now " --host=aarch64-none-linux-android --disable-shared && E:\work\Android\sdk\cmake\3.6.4111459\bin\cmake.exe -E touch D:/tincapp-master/app/.externalNativeBuild/cmake/debug/arm64-v8a/lzo-prefix/src/lzo-stamp/lzo-configure"
  'D:\tincapp-master\app\.externalNativeBuild\cmake\debug\arm64-v8a\lzo-prefix\src\lzo\configure' ????????????????????????е????
  ?????????????
  ninja: build stopped: subcommand failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

17 actionable tasks: 1 executed, 16 up-to-date

**Comment by pacien** [comment]
I'd suggest running the build process on Linux.

**Comment by CoterJiesen** [comment]
this command "CONFIGURE_COMMAND	<SOURCE_DIR>/configure ${xCONFIG} --disable-shared" in CMakeLists.txt only work in linux

**Comment by pacien** [comment]
Indeed, some dependencies require ´sh´ in their build process.
I added a note in the readme.
