### ISSUE TITLE
Even the node is connected all apps use normal Internet

### ISSUE THREAD

**Issue by Mannshoch** [pacien/tincapp#41]
I setup TincApp and was able to get a connection.  `ifconfig -a`  shows a tun0 with an IP, but all Data goes through the normal connection.
`IP-Address` and `Route` is set. `DNS Server`, `Search domains` and `Allow bypass` are set `no`

**Comment by pacien** [comment]
Could you provide your `network.conf` file?

Please also note that this issue tracker is meant for bug reports and feature requests only.
Assistance is provided through the IRC channel: `#tincapp` on freenode.net.

**Comment by Mannshoch** [comment]
```
Address = 172.16.1.2/16
Route = 172.16.0.0/24
DisallowApplication = com.nutomic.syncthingandroid
```
