### ISSUE TITLE
Android using wrong dns server when tinc is active

### ISSUE THREAD

**Issue by larsks** [pacien/tincapp#46]
I have tincapp running on two Android devices: a oneplus 3T running LineageOS 14.1 (Android 7.1.2), and a Huawei Mediapad M3 running EMUI 5.0.1 (Android 7.0).  Both devices have the same configuration, which includes in `network.conf`:

    DNSServer = 172.16.254.1

On my oneplus 3T, when tinc is active, DNS queries go, as desired, to the nameserver defined by the tinc configuration.  That is, running `tcpdump` on the VPN server itself (`172.16.254.1`), I can run `host hostname.only.on.vpn` in Termux on my phone and see the queries coming in over the vpn interface (and the hostname resolves correctly).

On my mediapad, the same query returns an `NXDOMAIN` error and the query is not visible on the server side.  Everything else seems to be working (that is, I can access hosts on the vpn by ip address just fine). It looks like on the mediapad, dns queries aren't going to the right server.

This smells more like an Android problem than a tinc problem, but do you have any idea what could be going on here?

**Comment by pacien** [comment]
It might be a cache issue or a conflict with another app (a DNS-based ad-blocker, a custom network manager, some app pre-installed by the manufacturer…) overriding the DNS settings.

**Comment by larsks** [comment]
It's not a DNS-based ad blocker. I don't *think* it's a cache issue (the behavior persists after a restart, for example).

I guess I can't rule out some sort of vendor-installed thing causing conflicts. I can try installing another VPN package and see if it experiences the same behavior.

**Comment by larsks** [comment]
...so for example, if I install and configure "OpenVPN Connect" with our corporate VPN, it looks like DNS is configured appropriately, and I can successfully resolve "internal only" hosts.

Let me know if there's anything that might help further diagnose this issue.

**Comment by larsks** [comment]
So after fiddling with this a bit more I've been able to make it work.  But I'm not sure I understand *why*.  In my `network.conf` I have:

    Address = 172.16.254.14/24

I assumed give this address, `tinc` would automatically add a route for the associated network (172.16.254.0/24).    It looks like it doesn't...sort of?  That is, without add `Route = 172.16.254.0/24`, I can still:

- Ping 172.16.254.1
- Perform DNS lookups manually by running `host some.internal.host 172.16.254.1`
- Connect to hosts that are *only* available via the vpn.

However, if I add to `network.conf`:

    Route = 172.16.254.0/24

Then:

- I see a new route show up in the `tun0` routing table.
- DNS lookups work correctly.
- Everything else continues to work exactly as it did before.

Looking at the routing tables in more detail:

**Without** the `Route` line, I see a route in table `main`:

    $ ip route show table main
    172.16.254.0/24 dev tun0 proto kernel scope link src 172.16.254.14

**With** the `Route` line, I see the same entry in the `main` table, but I also see a second entry in the interface-specific table:

```
$ ip rule list | grep tun0
11000:	from all iif tun0 lookup 97 
14000:	from all oif tun0 uidrange 0-10132 lookup 1010 
14000:	from all oif tun0 uidrange 10134-99999 lookup 1010 
$ ip route show table 1010
172.16.254.0/24 dev tun0  proto static  scope link 
```

Looking at the two rules, I'm not entirely sure why DNS *specifically* appears to require the second one. It seems as if both rules should accomplish the same thing (and the route in the `main` table is demonstrably working for everything *except* DNS).

**Comment by pacien** [comment]
`Address` configures the network interface, whereas `Route` configures routes in the proper tables, to enable some applications such as the VPN app itself to bypass the VPN connection.

Using only `Address`, no route is implicitely added by the app itself. In this case, the behaviour is specific to each Android version. For instance, nothing is added to the main routing table at all on Android L.
