### ISSUE TITLE
seeting button doest not working in tinc app

### ISSUE THREAD

**Issue by muhammadarif1** [pacien/tincapp#47]
#### Expected behavior
when the user presses the settings button the user should be able to set the vpn settings in accordance with the wishes of the user.
#### Actual behavior
when I try to press the settings button to set up the vpn connection the app crashes and stops
#### How to reproduce
- download tinc app 
- launch the app 
- go to setting button
- and app will get crased and stops

* Operating system: advan s5e nxt android lolipop 5.1 idos
* app version; tincn app v  0.12
#### Recording Of The Bug
https://www.youtube.com/watch?v=1lLWJE5aQCU
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@muhammadarif/seeting-button-doest-not-working-in-tinc-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by pacien** [comment]
Hello,
Could you post the application's logfile?
It is located at `Android/data/org.pacien.tincapp/cache/tincapp.log` on the device's public storage.

**Comment by pacien** [comment]
It seems that you managed to open the setting screen in issue #48.
How did you solved the problem?

**Comment by muhammadarif1** [comment]
if just installed I can open it ,,
but when the application is
installed more than 1 hour the
problem will reappear

Pada tanggal Kam, 22 Mar 2018 14:56, Notkea <notifications@github.com>
menulis:

**Comment by pacien** [comment]
Is your device properly able to read and write on its secondary storage?
Please check that there is enough space available on it too.

**Comment by pacien** [comment]
Unreproducible/implausible: might be due to a broken environment.
