### ISSUE TITLE
bug found in tich app whento create new networks

### ISSUE THREAD

**Issue by muhammadarif1** [pacien/tincapp#48]
#### Expected behavior
This application allows users to generate node and key configurations. this feature can be found in the settings option

#### Actual behavior
when i tried tu use that feature. when I want to create a new network, this application get crashed and stop itself

#### How to reproduce
- download tinch app
- laucnh the app 
- go to setting option 
- chose features generate node configurations and key
- after that try to create new networ and a app will crashed
* Browser:  tinc app v 0. 12
* Operating system: android 5.1 idos advan s5e nxt

#### Recording Of The Bug
https://www.youtube.com/watch?v=dXQTfO-EQVA

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@muhammadarif/bug-found-in-tich-app-whento-create-new-networks">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by pacien** [comment]
Hello, and again, please provide the logfiles.

**Comment by muhammadarif1** [comment]
Log file is blank

Pada tanggal Kam, 22 Mar 2018 14:48, Notkea <notifications@github.com>
menulis:

**Comment by pacien** [comment]
Unreproducible/implausible: might be due to a broken environment.
