### ISSUE TITLE
No notification area indication

### ISSUE THREAD

**Issue by gerroon** [pacien/tincapp#61]
Hi

Tinc app use to have a display in the notification tray while it is connected when I used it on Lollipop. I moved to Linegae OS 14.1 and now I do not see thetray notification when I connect to my VPN. I do not know what it is actually called, but it had "disconnect" optiopn on it. I am wondering if this is a bug.

Thanks

**Comment by pacien** [comment]
This is not a bug. Android used to display a standard notification when a VPN connection was active. Newer versions of the OS have a more discreet indicator that only shows up when opening the quick settings drop-down.

![15342428274384](https://user-images.githubusercontent.com/1449319/44087041-cbbf27a0-9fbe-11e8-906a-2ddfd91bb922.png)

**Comment by gerroon** [comment]
Sure, but Openvpn still shows that tray notification I mentioned.

**Comment by pacien** [comment]
That's strange. It should either show a notification or an indicator like on the screenshot above.

**Comment by gerroon** [comment]
I get the indicator, but the indicator does not let me disconnect, it opens the system's VPN settings page when I tap on it.

**Comment by pacien** [comment]
In the opened system VPN settings window, you can tap on the Tinc App entry and choose to disconnect. You can also do that from the application itself by tapping on the disconnect icon on the top bar.

**Comment by gerroon** [comment]
Pacien, yes I understand that but what I am saying is that Openvpn app provides the notification tray when connected on Lineage OS, Tinc app lost that feature in LineageOS 14.1. 

This is really just a convenience feature request, nothing curial for sure.

**Comment by pacien** [comment]
I have no control over the way the system displays this notification/indicator.
IMHO, the new discreet and compact way seems better, even though it requires extra clicks to disconnect.

**Comment by gerroon** [comment]
Ok thanks
