### ISSUE TITLE
Route parameter doesn't do anything (Android 8.1, Oneplus 5T)

### ISSUE THREAD

**Issue by stylemistake** [pacien/tincapp#68]
My Tinc setup is fairly simple: all hosts share a `10.1.0.0/24` subnet, root node is `10.1.0.2`, and my phone is `10.1.0.4`.

Here's a snippet of `network.conf`:

```
Address = 10.1.0.4/32
Route = 10.1.0.0/24
AllowBypass = true
```

Pings work well for `10.1.0.4` (self), but get lost when pinging `10.1.0.2`.

As I discovered, this parameter actually has no effect.

This is the output of `ip route` on the phone console (notice that tinc route is missing):
```bash
$ ip route
10.0.0.0/24 dev wlan0  proto kernel  scope link  src 10.0.0.4 ## <-- home network (not tinc!)
```

This is the status screen of the Tinc app:
![tinc screenshot](https://user-images.githubusercontent.com/1516236/44779751-fa6ab800-ab88-11e8-82ac-8ff033f61b82.png)

Maybe i'm doing something wrong, but I can't get this thing to work :disappointed: 

Any help appreciated.

**Comment by pacien** [comment]
Hello,

From the [FAQ](http://tincapp.pacien.org/faq.html):

> Route not shown with `route` or `ip route`
    Routes are added to an Android-managed routing table, entries from which are not listed by default. Use `ip route list table all` to list entries from all routing tables.

You might also want to take a look at the [troubleshooting guide](http://tincapp.pacien.org/troubleshooting.html).

For further assistance, I invite you to continue on the IRC channel: #tincapp on freenode.
