### ISSUE TITLE
Send ALRM to tinc process on network change

### ISSUE THREAD

**Issue by BrainDamage** [pacien/tincapp#70]
Tinc has an exponential backoff time to re-try connection on network failure. If the network is unavailable for long, this timer can reach tens of minutes. However, tincd also supports listening for ALRM signal and attempt to re-connect to all nodes immediately. It'd be nice if tincapp would listen for network changes on the android side and send ALRM to tinc every time one happens, making VPN link re-connection much faster and seamless.

**Comment by pacien** [comment]
Note to self: use `tinc retry`.

**Comment by pacien** [comment]
Added in commit 9a5fcf6, to be included in v0.21.
