### ISSUE TITLE
LogLevel setting ignored

### ISSUE THREAD

**Issue by bellocarico** [pacien/tincapp#74]
Now that my device connects properly I would like to decrease the verbosity of the tinc daemon to reduce storage utilisation. Following the documentation:

> "The verbosity of the logging can be set by using the LogLevel configuration option in tinc.conf."

However adding

**LogLevel = 0**

into the tinc.conf appears not to be effective and the device keeps operating on **LogLevel: Debug**

**Comment by pacien** [comment]
The `LogLevel` setting only affects the verbosity of the stored logs.
The viewer interface always prints logs at debug level, without storing the output.
