### ISSUE TITLE
Chromebook Support

### ISSUE THREAD

**Issue by rkeene** [pacien/tincapp#75]
Possibly out of scope, but I am interested in using this on a Chromebook.  I setup the Android version on my Chromebook but this only allowed Android apps to access the VPN.

Is there any chance of a ChromiumOS port ?

**Comment by pacien** [comment]
[Chromium OS' VPN API][1] are very different from the ones exposed on the Android platform.

The former uses events and function calls to pass network packets while the latter exposes a classical tun interface (directly giving access to a corresponding file descriptor). A new (very simple) [device driver][2] would be needed in tinc itself to support this particular network interface for Chromium OS.

The user interface that Tinc App provides does not seem to fit the other OS either.

This looks like a whole new port completely separate from this one.

[1]: https://developer.chrome.com/apps/vpnProvider
[2]: https://github.com/gsliepen/tinc/blob/1.1/src/device.h

**Comment by rkeene** [comment]
Is there any possibility that you are interested in creating this port ?  I am willing to donate towards its creation if that's helpful.

**Comment by rkeene** [comment]
It looks like the Android VPN solution is supposed to support this and it's just a bug in ChromeOS 69, so it should work with the next ChromeOS update !
