### ISSUE TITLE
Unable to get VPN working

### ISSUE THREAD

**Issue by Daniel15** [pacien/tincapp#76]
I have tinc installed on a few computers and it's working great. Now I'm trying to get it working on my phone.

The config seems fine:
![](https://i.imgur.com/abVZPtE.jpg)
![](https://i.imgur.com/N0pG8E0.jpg) 
![](https://i.imgur.com/MXbwnhk.jpg)

But I'm unable to hit any of the hosts on the VPN. For example, if I go to http://10.123.1.1/ in a browser, it never loads (this works fine from other systems on the VPN).

Any ideas?

**Comment by pacien** [comment]
Hello,
Have you tried following the [troubleshooting guide](https://tincapp.pacien.org/troubleshooting.html)?
In particular, you might want to check the system and tinc's internal routing rules in both directions.
From what I see on the last screenshot, you might be missing a `Subnet` for your phone.
For further assistance, I invite you to continue on the IRC channel (`#tincapp` on `irc.freenode.net`).

**Comment by Daniel15** [comment]
Thanks for the reply! I'm on vacation at the moment but once I'm back I'll look further into the troubleshooting guide :)

**Comment by Daniel15** [comment]
> From what I see on the last screenshot, you might be missing a Subnet for your phone.

That was exactly the problem! Added `Subnet = 10.123.1.7/32` to the phone's host config and it works now. Thank you @pacien 😃
