### ISSUE TITLE
Route Problem on Galaxy Note 8

### ISSUE THREAD

**Issue by mshsoft** [pacien/tincapp#77]
Hi all
I got it working fairly easily on Galaxy Note 8. But, despite being able to ping both parties, I cannot get any packet to any other destination to get out of the phone. It seems that the Route option in network.conf does not do anything. Yeah, I know that android keeps it somewhere else and I have to see the routes with "ip route list table all" and it does add some entries for tun0, but no traffic destined for any address except the VPN subnet passes through. 
Strangely, DNS works, I can resolve DNS queries on the phone. I have installed a dns server on the other end, so some packets can go through. But web traffic, etc. , cannot!
I have attached the config files and the logs:

Mobile App Config files:
[network.conf.txt](https://github.com/pacien/tincapp/files/2722272/network.conf.txt)
[tinc.conf.txt](https://github.com/pacien/tincapp/files/2722273/tinc.conf.txt)
![screenshot_20190103-014404_tinc app](https://user-images.githubusercontent.com/46331573/50616063-34174b00-0efc-11e9-947f-e073128b5f1d.jpg)

host files:
[appclient1.txt](https://github.com/pacien/tincapp/files/2722279/appclient1.txt)
[appserver.txt](https://github.com/pacien/tincapp/files/2722280/appserver.txt)

Traffic at the server side when a web page is requested on the mobile :
![traffic_at_the_server_side](https://user-images.githubusercontent.com/46331573/50616378-7c833880-0efd-11e9-8647-2d8e0611094c.jpg)

as you can see, DNS traffic passes through, since the directive in network.conf works, and I have a dns server set up at the other side, but normal traffic cannot be routed.

Routes:
![routes_on_the_mobile_phone](https://user-images.githubusercontent.com/46331573/50616715-ec45f300-0efe-11e9-8e56-2743030c15a1.jpg)

**Comment by pacien** [comment]
Hello,

If you want all packets from `appclient1` to be routed to `appserver`, you also need to add a corresponding catch-all `Subnet = 0.0.0.0/0` to `appserver`'s host file.

Furthermore, I notice some minor issues in the other files:
* `appclient1`: the prefix length `/32` is missing in the `Subnet` parameter.
* `tinc.conf`: the device parameter is useless on Android.

If further assistance is needed, I invite you to continue over IRC: `#tincapp` on `irc.freenode.net`.

**Comment by mshsoft** [comment]
works like a charm. Thanks buddy
