### ISSUE TITLE
Wifi/USB tether request

### ISSUE THREAD

**Issue by eldadh** [pacien/tincapp#78]
i am trying to use the vpn while tethering my laptop either via USB or wifi,
how can i make sure the tethered traffic goes through the tunnel/s as well?

i have enabled bypass in the conf file.
however the trace route on the laptop shows that after the "phone hop" it goes through the normal provider APN and not the VPN tunnel.

thnx eldadh

**Comment by pacien** [comment]
Hello,

From [the FAQ](https://tincapp.pacien.org/faq.html):
> Tethering?
>    It is still possible to share a mobile connection while the VPN is active. AllowBypass = true must be set in the network.conf file. However, the shared connection will not be tunneled. Third party applications or custom firewall rules can be used to share the VPN connection with tethered devices.

The Android system does not allow the VPN connection to be shared to a tethered device.
Tinc needs to be ran on said device as well. Alternatively, `iptables` rules could be set on a rooted phone to channel everything in the VPN.
