### ISSUE TITLE
"Storage access: permission denied" on Android-x86

### ISSUE THREAD

**Issue by 2n8asm** [pacien/tincapp#79]
When I try to generate node configuration and keys, I got this error:

> Could not create directory /storage/emulated/0/Android/data/org.pacien.tincapp/files/2n8asm: Permission denied

When I run `adb shell pm grant org.pacien.tincapp android.permission.WRITE_EXTERNAL_STORAGE`, I got this error:

> Operation not allowed: java.lang.SecurityException: Package org.pacien.tincapp has not requested permission android.permission.WRITE_EXTERNAL_STORAGE

I think it is necessary to add `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` to `AndroidManifest.xml`(See [this](https://developer.android.com/training/data-storage/files#ExternalStoragePermissions).)

**Comment by pacien** [comment]
Hello,

This permission isn't necessary for the app to write on its dedicated directory on either the internal or external storage.

> Beginning with Android 4.4 (API level 19), reading or writing files in your app's private external storage directory—accessed using getExternalFilesDir()—does not require the READ_EXTERNAL_STORAGE or WRITE_EXTERNAL_STORAGE permissions.
> – the documentation

Note that some Android distributions such as Android-x86 do not implement filesystem permissions correctly on the external storage. This is a bug that should be reported to them and fixed on their side.

A possible workaround that we could implement would be to request this permission conditionally at run-time. A pull request for this would be welcomed.

**Comment by pacien** [comment]
FAQ entry added:
> Permission denied on external storage
>    Some Android distributions such as Android-x86 do not implement file access permissions correctly. On those ROMs, it is necessary to manually grant the Storage permission to the application in the System settings.

**Comment by rwky** [comment]
For anyone else finding this, I had to do it on my Samsung Galaxy S10.
