### ISSUE TITLE
Connections not going through

### ISSUE THREAD

**Issue by wolfy1339** [pacien/tincapp#95]
The client can connect to other nodes, but I can't use the tinc addresses from other apps.

For instance, in Firefox if I try to load the IP of a tinc node running a webserver, the request times out

**Comment by pacien** [comment]
I suspect a configuration issue. Have you tried going through the [troubleshooting guide](https://tincapp.pacien.org/troubleshooting.html)?

In particular, you might want to check that the routes in network.conf are correctly defined.

**Comment by wolfy1339** [comment]
Everything in `network.conf` is proper. It's a brand new config as well

**Comment by pacien** [comment]
Could you post your configuration, redacting private information?
Also it would be better to continue over either the IRC or the Matrix support channel.

**Comment by pacien** [comment]
I believe that this issue can be closed. Feel free to reach out over the channels.

**Comment by u6bkep** [comment]
Was this problem ever resolved? I am having the same problem since updating to Android 10, and would like to know what solved Wolfy's issue.

**Comment by pacien** [comment]
For reference, @u6bkep's issue was due to a missing configuration key.
The app seems to work fine on Android 10.
